sudo: true                  # Required to install packages

env:
  global:
    - UML_DOCKERCOMPOSE=1   # Install docker-compose

install:
  # Install https://github.com/moul/travis-docker toolchain
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - ./run 'docker-compose up -d blog && docker ps && date'
#  - ./run 'docker-compose run web npm test'

deploy:
  provider: npm
  email: developer@agcocorp.com
  api_key:
    secure: "ZOFUbJMY9nu1ekRB51bpSMm3DgOsIf3TrqFrW4YflLnLzWIGQTT/K7p+Fjw+uf3GMNojrH8sTT1TyBustt08fobm0iRQq1FhT0xRzz+NsAqGC+DdbbNyUYoKvKGJ3sFvX0XJc65eFu5Zafaf9XidubG9l44INEkNGmpzwY5zy+M="
  on:
    tags: true
    repo: agco/harvesterjs
    branch: master

