mongo1:
  hostname: mongo1
  image: mongo:2.6.4
  entrypoint: [ "mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27017:27017"
    - "28017:28017"
  restart: always

# This configures the MongoDB replicaset
mongosetup:
  image: mongo:2.6.4
  links:
    - mongo1:mongo1
  volumes:
    - ./scripts:/scripts
  entrypoint: [ "/scripts/setup.sh" ]

# Verify reading and writing
# Run 'docker logs -f elasticmongo_verify_1' to see what it outputs.
verify:
  image: mongo:2.6.4
  links:
    - mongo1:mongo1
  volumes:
    - ./scripts:/scripts
  entrypoint: [ "/scripts/query.sh" ]

msh:
  image: mongo:2.6.4
  links:
    - mongo1:mongo1
  command: mongo --host mongo1

cache:
  image: ubuntu-debootstrap:14.04
  volumes:
    - /cache
  command: echo

web:
  build: kristofsajdak/buildstep
  volumes_from:
      - cache
  volumes:
    - .:/local-app
    - ./env:/local-env
  environment:
    PORT: 9000
  ports:
    - "9000:9000"
  links:
    - mongo1